import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../../components/Nav";
import { Toaster as Sonner } from "sonner";
import { CircleX } from "lucide-react";
import { CircleCheckIcon } from "lucide-react";

import { Navbar } from "../../components/Navbar/Navbar";
import FirstHeader from "../../components/FirstHeader";
import Footer from "../../components/Footer";
import { Footer2 } from "../../components/Footer2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="flex flex-col min-h-screen max-w-screen-xl w-full p-3 mx-auto sm:p-5">
          {/* <Nav /> */}

        {/* <div className="flex flex-col min-h-screen  w-full "> */}
          {/* // <Nav /> */}
          <div>
          <Navbar />
          {/* <FirstHeader /> */}
          </div>
     

        <main className="flex-grow">
        {children}
        </main>
        <div>
        <Footer2 />
      
      
        </div>
       
        <Sonner
       
        toastOptions={{classNames:{

          closeButton:"",
          title:"text-sm",
          content:"border-[1.5] border-green-500",
          default:"text-blue-500",
         icon:"size-4",

          success:"border-2 border-green-200  bg-green-100 text-green-400",
          error:"border-2 border-red-200  bg-red-100 text-red-400"
        }}}
        
          closeButton
            //  richColors
         className=""
          icons={{

             info:<CircleX className="" />,
            error: <CircleX className="" />,
            success: <CircleCheckIcon className="" />,
          }}
        />
        </div>
       
         
        </body>
    </html>
  );
}
